name: Keepy Uppy
options:
  createIntermediateGroups: true
targets:
  Keepy Uppy:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Sources
      - Shared
      - Resources/Assets.xcassets
      - path: Launchd/au.com.workwireless.keepy-uppy.helper.plist
        buildPhase:
          copyFiles:
            destination: wrapper
            subpath: Contents/Library/LaunchDaemons
    dependencies:
      - target: KeepyUppyHelper
        embed: true
        codeSign: true
        copy:
          destination: executables
      - target: keepy-uppy
        embed: true
        codeSign: true
        copy:
          destination: executables
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: au.com.workwireless.keepy-uppy
        PRODUCT_MODULE_NAME: KeepyUppy
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Manual
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  Keepy UppyTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Tests
    dependencies:
      - target: Keepy Uppy
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  KeepyUppyHelper:
    type: tool
    platform: macOS
    deploymentTarget: "13.0"
    sources: [Helper, Shared]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: au.com.workwireless.keepy-uppy.helper
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Manual
        SWIFT_VERSION: "5.0"

  keepy-uppy:
    type: tool
    platform: macOS
    deploymentTarget: "13.0"
    sources: [CLI, Shared]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: au.com.workwireless.keepy-uppy.cli
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Manual
        SWIFT_VERSION: "5.0"
schemes:
  Keepy Uppy:
    build:
      targets:
        Keepy Uppy: all
        Keepy UppyTests: [test]
    run:
      config: Debug
    test:
      targets:
        - Keepy UppyTests
    archive:
      config: Release
